string="Hello, World!"
print(string)
print(max(string))
print(min(string))
print(len(string))
print(" " in string)
print(string[0])
print(string[-1])
print(string[::-1])
print(string.split(","))
print(string*2)
print(string.upper())
print(string.lower())
print(string.replace("World","Python"))
print(string.find("World"))
print(string.capitalize())